In [2]:
import numpy as np


In [ ]:
# Python List -> np.array()

np_arr = np.array(python_list)

"""
Numpy는 다차원 배열 작업을 지원하므로 배열을 다룰 때 유용하다.
"""

In [9]:
# np.arr의 원소들의 합  : np.sum(np_arr)


data = [10, 25, 40, 55, 70]
np_arr = np.array(data)
arr_sum = np.sum(np_arr)
print(arr_sum)
print("----")
# 
np_2d = np.array([[1,2,3],[4,5,6]])
print(np_2d)
np_2d_sum_0 = np.sum(np_2d)

np_2d_sum_1 = np.sum(np_2d, axis=1)
print('--np.sum--')
print("axis=0 :",np_2d_sum_0)
print("axis=1 :",np_2d_sum_1)


200
----
[[1 2 3]
 [4 5 6]]
--np.sum--
axis=0 : 21
axis=1 : [ 6 15]


In [11]:
# len(np_arr)
arr_l = len(np_arr)
avr_arr = arr_sum/arr_l
print(avr_arr)

40.0


In [14]:
# np.arr의 차원 확인  np_arr.shape : 배열의 각 차원의 크기를 tuple에 담아 반환한다.

np_2d = np.array([[1,2,3],[4,5,6]])

np_2d_dim = np_2d.shape
print(np_2d_dim)

(2, 3)


In [24]:
# 배열에 담긴 총 원소의 개수 : np_arr.size
np_2d = np.array([[1,2,3],[4,5,6]])

print(np_2d.size)

6


In [16]:
# np.mean(np_arr) : 평균구하기
# axis =0
# axis =1

np_2d = np.array([[1,2,3],[4,5,6]])
mean_0 = np.mean(np_2d)
mean_1 = np.mean(np_2d, axis=1)

print("mean_0 : ", mean_0)
print("mean_1 : ", mean_1) #각 행의 평균을 반환

mean_0 :  3.5
mean_1 :  [2. 5.]


In [17]:
#np.max(np_arr)
#np.min(np_arr)

my_array = np.array([1, 5, 3, 7, 2, 8, 4])

# 배열의 최댓값과 최솟값 계산
max_value = np.max(my_array)
min_value = np.min(my_array)

# 결과 출력
print("배열의 최댓값:", max_value)
print("배열의 최솟값:", min_value)

my_2d_array = np.array([[1, 2, 3], [4, 5, 6]])

# 각 열(axis=0)의 최댓값과 최솟값 계산
max_along_columns = np.max(my_2d_array, axis=0)
min_along_columns = np.min(my_2d_array, axis=0)

# 각 행(axis=1)의 최댓값과 최솟값 계산
max_along_rows = np.max(my_2d_array, axis=1)
min_along_rows = np.min(my_2d_array, axis=1)

# 결과 출력
print("각 열의 최댓값:", max_along_columns)
print("각 열의 최솟값:", min_along_columns)
print("각 행의 최댓값:", max_along_rows)
print("각 행의 최솟값:", min_along_rows)

배열의 최댓값: 8
배열의 최솟값: 1
각 열의 최댓값: [4 5 6]
각 열의 최솟값: [1 2 3]
각 행의 최댓값: [3 6]
각 행의 최솟값: [1 4]


In [20]:
# np.divide(np_arr, k) -> 각 원소를 k로 나눈 값을 담은 np_arr반환
my_array = np.array([10, 20, 30, 40, 50])

# 각 원소를 10으로 나눈 결과를 담은 새로운 NumPy 배열 생성
result_array = np.divide(my_array, 10)

# 결과 출력
print(result_array)
print('***___***___')

my_array = np.array([10, 20, 30, 40, 50])

# 각 원소를 10으로 나눈 결과를 담은 새로운 NumPy 배열 생성
result_array = my_array / 10

# 결과 출력
print(result_array)

[1. 2. 3. 4. 5.]
***___***___
[1. 2. 3. 4. 5.]


In [23]:
# np.power(np_arr, k) : 각 원소의 k승한 np_arr 반환

my_arr = np.array([2,3,4,5,6])

print(np.power(my_arr, 2))

[ 4  9 16 25 36]
